"""
CEFR Vocabulary Database
Comprehensive vocabulary lists organized by CEFR levels (A1-C1)
Based on ESL Lounge and Oxford Learner's Dictionary word lists
"""

class CEFRVocabulary:
    """Comprehensive CEFR vocabulary database"""
    
    def __init__(self):
        self.vocabulary_levels = {
            'A1': self._get_a1_words(),
            'A2': self._get_a2_words(), 
            'B1': self._get_b1_words(),
            'B2': self._get_b2_words(),
            'C1': self._get_c1_words(),
        }
    
    def _get_a1_words(self):
        """A1 Elementary level words - basic everyday vocabulary"""
        return {
            # Basic words for beginners (approximately 500-700 words)
            'a', 'about', 'above', 'across', 'action', 'activity', 'actor', 'actress', 'add', 'address', 
            'adult', 'advice', 'afraid', 'after', 'afternoon', 'again', 'age', 'ago', 'agree', 'air', 
            'airport', 'all', 'also', 'always', 'amazing', 'and', 'angry', 'animal', 'another', 'answer',
            'any', 'anyone', 'anything', 'apartment', 'apple', 'april', 'are', 'area', 'arm', 'around',
            'arrive', 'art', 'article', 'artist', 'as', 'ask', 'at', 'august', 'aunt', 'autumn',
            'baby', 'back', 'bad', 'bag', 'ball', 'banana', 'band', 'bank', 'bar', 'basketball',
            'bath', 'bathroom', 'be', 'beach', 'beautiful', 'because', 'become', 'bed', 'bedroom', 'beer',
            'before', 'begin', 'beginning', 'behind', 'believe', 'below', 'best', 'better', 'between',
            'bicycle', 'big', 'bike', 'bill', 'bird', 'birthday', 'black', 'blue', 'boat', 'body',
            'book', 'boring', 'born', 'bottle', 'box', 'boy', 'bread', 'break', 'breakfast', 'bring',
            'brother', 'brown', 'build', 'bus', 'business', 'busy', 'but', 'butter', 'buy', 'by',
            'cafe', 'cake', 'call', 'can', 'car', 'card', 'care', 'careful', 'carry', 'case',
            'cat', 'catch', 'cd', 'centre', 'century', 'chair', 'change', 'chat', 'cheap', 'cheese',
            'chicken', 'child', 'children', 'chocolate', 'choose', 'cinema', 'city', 'class', 'clean',
            'clear', 'climb', 'clock', 'close', 'clothes', 'club', 'coat', 'coffee', 'cold', 'college',
            'colour', 'come', 'comfortable', 'computer', 'concert', 'cook', 'cool', 'copy', 'corner',
            'correct', 'cost', 'could', 'country', 'course', 'cousin', 'create', 'cry', 'cup', 'cut',
            'dad', 'dance', 'dangerous', 'dark', 'date', 'daughter', 'day', 'dead', 'dear', 'december',
            'decide', 'decision', 'deep', 'definitely', 'dentist', 'design', 'desk', 'diary', 'dictionary',
            'die', 'different', 'difficult', 'dinner', 'direction', 'dirty', 'dish', 'do', 'doctor',
            'document', 'dog', 'door', 'down', 'draw', 'dress', 'drink', 'drive', 'driver', 'drop',
            'dry', 'during', 'dvd', 'each', 'ear', 'early', 'easy', 'eat', 'education', 'eight',
            'eighteen', 'eighty', 'eleven', 'email', 'end', 'english', 'enjoy', 'enough', 'even',
            'evening', 'ever', 'every', 'everyone', 'everything', 'example', 'excited', 'exciting',
            'excuse', 'exercise', 'expensive', 'experience', 'explain', 'eye', 'face', 'fact', 'fail',
            'fall', 'family', 'famous', 'far', 'fast', 'fat', 'father', 'favourite', 'february',
            'feel', 'fifteen', 'fifty', 'fill', 'film', 'find', 'fine', 'finger', 'finish', 'fire',
            'first', 'fish', 'fit', 'five', 'flat', 'floor', 'flower', 'fly', 'follow', 'food',
            'foot', 'football', 'for', 'forget', 'forty', 'four', 'fourteen', 'free', 'fresh',
            'friday', 'friend', 'friendly', 'from', 'front', 'fruit', 'full', 'fun', 'funny',
            'furniture', 'game', 'garden', 'get', 'girl', 'give', 'glass', 'go', 'god', 'good',
            'grandfather', 'grandmother', 'great', 'green', 'grey', 'ground', 'group', 'grow',
            'guess', 'guitar', 'hair', 'half', 'hand', 'happen', 'happy', 'hard', 'hat', 'hate',
            'have', 'he', 'head', 'health', 'healthy', 'hear', 'heart', 'heavy', 'hello', 'help',
            'her', 'here', 'hi', 'high', 'him', 'his', 'history', 'hit', 'hobby', 'hold', 'holiday',
            'home', 'hope', 'horrible', 'horse', 'hospital', 'hot', 'hotel', 'hour', 'house', 'how',
            'hundred', 'hungry', 'hurt', 'husband', 'i', 'ice', 'idea', 'if', 'ill', 'important',
            'in', 'information', 'inside', 'instead', 'interested', 'interesting', 'international',
            'internet', 'interview', 'into', 'is', 'island', 'it', 'its', 'january', 'job', 'join',
            'july', 'june', 'just', 'keep', 'key', 'kill', 'kind', 'kitchen', 'know', 'lake', 'land',
            'language', 'large', 'last', 'late', 'laugh', 'learn', 'leave', 'left', 'leg', 'less',
            'let', 'letter', 'library', 'lie', 'life', 'light', 'like', 'line', 'lion', 'listen',
            'little', 'live', 'long', 'look', 'lose', 'lot', 'loud', 'love', 'low', 'lunch',
            'machine', 'magazine', 'make', 'man', 'many', 'map', 'march', 'may', 'me', 'meal',
            'mean', 'meat', 'meet', 'member', 'menu', 'message', 'middle', 'milk', 'mind', 'mine',
            'minute', 'miss', 'mistake', 'mobile', 'model', 'moment', 'monday', 'money', 'month',
            'more', 'morning', 'most', 'mother', 'move', 'movie', 'much', 'mum', 'music', 'must',
            'my', 'name', 'nature', 'near', 'need', 'never', 'new', 'news', 'newspaper', 'next',
            'nice', 'night', 'nine', 'nineteen', 'ninety', 'no', 'nobody', 'noise', 'normal',
            'north', 'nose', 'not', 'note', 'nothing', 'notice', 'november', 'now', 'number',
            'october', 'of', 'off', 'office', 'often', 'oh', 'ok', 'old', 'on', 'once', 'one',
            'only', 'open', 'or', 'orange', 'order', 'other', 'our', 'out', 'over', 'own',
            'page', 'paint', 'paper', 'parent', 'park', 'part', 'party', 'pass', 'past', 'pay',
            'pen', 'pencil', 'people', 'perfect', 'perhaps', 'person', 'phone', 'photo', 'piano',
            'pick', 'picture', 'piece', 'pink', 'pizza', 'place', 'plan', 'plant', 'play', 'please',
            'police', 'poor', 'popular', 'post', 'potato', 'pound', 'practice', 'present', 'pretty',
            'price', 'problem', 'product', 'programme', 'project', 'pub', 'pull', 'purple', 'push',
            'put', 'question', 'quick', 'quickly', 'quiet', 'quite', 'radio', 'rain', 'read',
            'ready', 'real', 'really', 'reason', 'red', 'remember', 'repeat', 'restaurant', 'return',
            'rice', 'rich', 'ride', 'right', 'ring', 'river', 'road', 'room', 'run', 'sad',
            'safe', 'same', 'saturday', 'save', 'say', 'school', 'science', 'sea', 'season', 'second',
            'see', 'seem', 'sell', 'send', 'september', 'seven', 'seventeen', 'seventy', 'she',
            'shop', 'shopping', 'short', 'should', 'show', 'sick', 'sing', 'single', 'sir', 'sister',
            'sit', 'situation', 'six', 'sixteen', 'sixty', 'size', 'sleep', 'slow', 'small', 'smile',
            'snow', 'so', 'soap', 'social', 'sofa', 'some', 'somebody', 'someone', 'something',
            'sometimes', 'son', 'song', 'soon', 'sorry', 'sound', 'soup', 'south', 'space', 'speak',
            'special', 'spend', 'sport', 'spring', 'start', 'station', 'stay', 'still', 'stop',
            'story', 'street', 'strong', 'student', 'study', 'stupid', 'subject', 'sugar', 'summer',
            'sun', 'sunday', 'supermarket', 'sure', 'swim', 'table', 'take', 'talk', 'tall', 'tea',
            'teach', 'teacher', 'team', 'telephone', 'television', 'tell', 'ten', 'terrible', 'test',
            'text', 'than', 'thank', 'that', 'the', 'theatre', 'their', 'them', 'then', 'there',
            'these', 'they', 'thing', 'think', 'third', 'thirteen', 'thirty', 'this', 'those',
            'three', 'through', 'thursday', 'ticket', 'time', 'tired', 'to', 'today', 'together',
            'tomato', 'tomorrow', 'tonight', 'too', 'train', 'travel', 'tree', 'trip', 'true',
            'try', 'tuesday', 'turn', 'twelve', 'twenty', 'two', 'understand', 'university', 'until',
            'up', 'us', 'use', 'useful', 'usually', 'very', 'video', 'village', 'visit', 'wait',
            'wake', 'walk', 'want', 'war', 'warm', 'wash', 'watch', 'water', 'way', 'we', 'wear',
            'weather', 'website', 'wedding', 'wednesday', 'week', 'weekend', 'welcome', 'well',
            'west', 'what', 'when', 'where', 'which', 'white', 'who', 'why', 'wife', 'win', 'window',
            'wine', 'winter', 'with', 'without', 'woman', 'wonderful', 'word', 'work', 'world',
            'worry', 'worse', 'worst', 'write', 'wrong', 'year', 'yellow', 'yes', 'yesterday',
            'yet', 'you', 'young', 'your'
        }
    
    def _get_a2_words(self):
        """A2 Pre-intermediate level words - expanding basic vocabulary"""
        # Note: A2 builds on A1, these are additional words
        return {
            'abroad', 'accent', 'accident', 'accommodation', 'according', 'across', 'active', 'actor',
            'actual', 'actually', 'ad', 'addition', 'address', 'adult', 'adventure', 'advertisement',
            'advice', 'afford', 'afterwards', 'against', 'agency', 'agent', 'agreement', 'agriculture',
            'ahead', 'aircraft', 'airline', 'airport', 'alarm', 'alcohol', 'alive', 'although',
            'amazing', 'amount', 'angry', 'anniversary', 'announce', 'annoying', 'annual', 'another',
            'anxiety', 'anxious', 'anyone', 'anywhere', 'apartment', 'apologise', 'appear', 'application',
            'appointment', 'appreciate', 'approach', 'approximately', 'architecture', 'area', 'argue',
            'argument', 'army', 'arrange', 'arrangement', 'arrest', 'arrival', 'arrive', 'article',
            'artificial', 'artist', 'as', 'ashamed', 'ask', 'asleep', 'atmosphere', 'attach', 'attack',
            'attempt', 'attend', 'attention', 'attitude', 'attract', 'attractive', 'audience', 'aunt',
            'author', 'automatic', 'available', 'average', 'avoid', 'awake', 'aware', 'away'
        }
    
    def _get_b1_words(self):
        """B1 Intermediate level words"""
        return {
            'absolutely', 'academic', 'access', 'accommodation', 'account', 'achievement', 'act', 'ad',
            'addition', 'admire', 'admit', 'advanced', 'advise', 'afford', 'age', 'aged', 'agent',
            'agreement', 'ahead', 'aim', 'alarm', 'album', 'alcohol', 'alcoholic', 'alternative',
            'amazed', 'ambition', 'ambitious', 'analyse', 'analysis', 'announce', 'announcement',
            'annoy', 'annoyed', 'annoying', 'apart', 'apologise', 'application', 'appointment',
            'appreciate', 'approximately', 'arrest', 'arrival', 'assignment', 'assist', 'atmosphere',
            'attach', 'attitude', 'attract', 'attraction', 'authority', 'average', 'award', 'aware',
            'balance', 'band', 'bang', 'bark', 'basic', 'basis', 'battle', 'beat', 'bedroom',
            'behave', 'behaviour', 'belong', 'benefit', 'beyond', 'billion', 'bite', 'bitter',
            'blame', 'blank', 'block', 'blow', 'board', 'boil', 'bomb', 'bone', 'boost', 'border',
            'borrow', 'boss', 'bother', 'bottom', 'bowl', 'brain', 'branch', 'brand', 'brave',
            'breath', 'breathe', 'breed', 'brick', 'brief', 'briefly', 'bright', 'brilliant', 'broad',
            'brother', 'brush', 'budget', 'build', 'burn', 'burst', 'bury', 'button', 'buzz',
            'cable', 'calm', 'campaign', 'cancer', 'candidate', 'capable', 'capital', 'captain',
            'capture', 'carbon', 'career', 'careful', 'careless', 'carpet', 'carry', 'case', 'cash',
            'cast', 'castle', 'casual', 'catch', 'category', 'cause', 'ceiling', 'celebration',
            'celebrity', 'cell', 'centre', 'century', 'ceremony', 'certain', 'certainly', 'chain',
            'chairman', 'challenge', 'champion', 'championship', 'chance', 'change', 'channel',
            'chapter', 'character', 'characteristic', 'charge', 'charity', 'chart', 'chat', 'cheap',
            'cheat', 'check', 'chemical', 'chemistry', 'chest', 'chief', 'childhood', 'chin', 'choice',
            'choose', 'citizen', 'claim', 'class', 'classic', 'classical', 'classroom', 'clean',
            'clear', 'clearly', 'click', 'client', 'climate', 'climb', 'clock', 'close', 'closed',
            'closely', 'clothes', 'clothing', 'cloud', 'club', 'clue', 'coach', 'coal', 'coast',
            'coat', 'code', 'coin', 'cold', 'collapse', 'colleague', 'collect', 'collection',
            'college', 'colour', 'column', 'combination', 'combine', 'come', 'comedy', 'comfort',
            'comfortable', 'command', 'comment', 'commercial', 'commission', 'commit', 'commitment',
            'committee', 'common', 'communicate', 'communication', 'community', 'company', 'compare',
            'comparison', 'compete', 'competition', 'competitor', 'complain', 'complaint', 'complete',
            'completely', 'complex', 'complicated', 'computer', 'concentrate', 'concentration',
            'concept', 'concern', 'concerned', 'concert', 'conclude', 'conclusion', 'condition',
            'conduct', 'conference', 'confidence', 'confident', 'confirm', 'conflict', 'confuse',
            'confused', 'confusing', 'confusion', 'connect', 'connection', 'conscious', 'consequence',
            'consider', 'considerable', 'considerably', 'consideration', 'consist', 'constant',
            'constantly', 'construct', 'construction', 'contact', 'contain', 'container', 'content',
            'contest', 'context', 'continue', 'contract', 'contrast', 'contribute', 'contribution',
            'control', 'conversation', 'cook', 'cookie', 'cooking', 'cool', 'cope', 'copy', 'core',
            'corner', 'correct', 'correctly', 'cost', 'cottage', 'cotton', 'cough', 'could',
            'council', 'count', 'counter', 'country', 'countryside', 'county', 'couple', 'courage',
            'course', 'court', 'cousin', 'cover', 'coverage', 'craft', 'crash', 'crazy', 'cream',
            'create', 'creation', 'creative', 'creature', 'credit', 'crime', 'criminal', 'crisis',
            'criticism', 'criticise', 'crop', 'cross', 'crowd', 'cruel', 'cry', 'culture', 'cup',
            'cure', 'curious', 'current', 'currently', 'curve', 'custom', 'customer', 'cut', 'cycle',
            'daily', 'damage', 'dance', 'danger', 'dangerous', 'dare', 'dark', 'darkness', 'data',
            'date', 'daughter', 'day', 'dead', 'deal', 'dealer', 'death', 'debate', 'debt', 'decade',
            'decide', 'decision', 'declare', 'decorate', 'decoration', 'decrease', 'deep', 'deeply',
            'defeat', 'defence', 'defend', 'degree', 'delay', 'deliberate', 'deliberately', 'delicious',
            'deliver', 'delivery', 'demand', 'demonstrate', 'dentist', 'department', 'departure',
            'depend', 'dependent', 'deposit', 'depress', 'depressed', 'depressing', 'depression',
            'depth', 'describe', 'description', 'desert', 'deserve', 'design', 'designer', 'desire',
            'desk', 'despite', 'destroy', 'destruction', 'detail', 'detailed', 'detect', 'detective',
            'determine', 'determined', 'develop', 'development', 'device', 'diagram', 'diamond',
            'diary', 'dictionary', 'die', 'diet', 'difference', 'different', 'differently', 'difficult',
            'difficulty', 'dig', 'digital', 'dinner', 'direct', 'direction', 'directly', 'director',
            'dirty', 'disadvantage', 'disagree', 'disappear', 'disappoint', 'disappointed',
            'disappointing', 'disappointment', 'disaster', 'discipline', 'discount', 'discover',
            'discovery', 'discuss', 'discussion', 'disease', 'dish', 'disk', 'dismiss', 'display',
            'distance', 'distribute', 'distribution', 'district', 'divide', 'division', 'divorce',
            'doctor', 'document', 'dog', 'domestic', 'door', 'double', 'doubt', 'down', 'download',
            'downstairs', 'downtown', 'dozen', 'draft', 'drag', 'drama', 'dramatic', 'draw', 'drawing',
            'dream', 'dress', 'dressed', 'drink', 'drive', 'driver', 'drop', 'drug', 'dry', 'due',
            'during', 'duty', 'each', 'ear', 'early', 'earn', 'earth', 'earthquake', 'easily', 'east',
            'eastern', 'easy', 'eat', 'economic', 'economics', 'economy', 'edge', 'edit', 'edition',
            'editor', 'education', 'educational', 'effect', 'effective', 'effectively', 'effort',
            'eight', 'eighteen', 'eighty', 'either', 'elderly', 'elect', 'election', 'electric',
            'electrical', 'electricity', 'electronic', 'element', 'elephant', 'eleven', 'else',
            'email', 'emerge', 'emergency', 'emotion', 'emotional', 'emphasis', 'emphasise',
            'employ', 'employee', 'employer', 'employment', 'empty', 'enable', 'end', 'enemy',
            'energy', 'engage', 'engaged', 'engine', 'engineer', 'engineering', 'english', 'enhance',
            'enjoy', 'enjoyable', 'enormous', 'enough', 'enquiry', 'ensure', 'enter', 'enterprise',
            'entertain', 'entertainment', 'enthusiasm', 'enthusiastic', 'entire', 'entirely',
            'entrance', 'entry', 'environment', 'environmental', 'episode', 'equal', 'equally',
            'equipment', 'error', 'escape', 'especially', 'essential', 'establish', 'estate',
            'estimate', 'even', 'evening', 'event', 'eventually', 'ever', 'every', 'everybody',
            'everyone', 'everything', 'everywhere', 'evidence', 'evil', 'exact', 'exactly', 'exam',
            'examination', 'examine', 'example', 'excellent', 'except', 'exception', 'exchange',
            'excited', 'excitement', 'exciting', 'exclude', 'excuse', 'execute', 'executive',
            'exercise', 'exhibition', 'exist', 'existence', 'existing', 'exit', 'expand', 'expect',
            'expectation', 'expected', 'expensive', 'experience', 'experienced', 'experiment',
            'expert', 'explain', 'explanation', 'explore', 'explosion', 'export', 'expose',
            'express', 'expression', 'extend', 'extension', 'extensive', 'extent', 'external',
            'extra', 'extraordinary', 'extreme', 'extremely', 'eye', 'face', 'facility', 'fact',
            'factor', 'factory', 'fail', 'failure', 'fair', 'fairly', 'faith', 'fall', 'false',
            'familiar', 'family', 'famous', 'fan', 'fancy', 'fantastic', 'far', 'farm', 'farmer',
            'farming', 'fashion', 'fashionable', 'fast', 'fat', 'father', 'fault', 'favour',
            'favourite', 'fear', 'feature', 'february', 'fee', 'feed', 'feedback', 'feel', 'feeling',
            'fellow', 'female', 'fence', 'festival', 'few', 'fiction', 'field', 'fifteen', 'fifty',
            'fight', 'figure', 'file', 'fill', 'film', 'final', 'finally', 'finance', 'financial',
            'find', 'finding', 'fine', 'finger', 'finish', 'fire', 'firm', 'first', 'fish', 'fishing',
            'fit', 'fitness', 'five', 'fix', 'fixed', 'flag', 'flat', 'flavour', 'flesh', 'flight',
            'float', 'flood', 'floor', 'flour', 'flow', 'flower', 'fly', 'flying', 'focus', 'fold',
            'folk', 'follow', 'following', 'food', 'foot', 'football', 'for', 'force', 'foreign',
            'forest', 'forever', 'forget', 'form', 'formal', 'format', 'former', 'formula', 'forth',
            'fortunate', 'fortunately', 'fortune', 'forty', 'forward', 'found', 'foundation',
            'four', 'fourteen', 'frame', 'free', 'freedom', 'freeze', 'frequently', 'fresh', 'friday',
            'friend', 'friendly', 'friendship', 'from', 'front', 'frozen', 'fruit', 'frustrate',
            'frustrated', 'frustrating', 'frustration', 'fuel', 'full', 'fully', 'fun', 'function',
            'fund', 'fundamental', 'funding', 'funny', 'furniture', 'further', 'furthermore',
            'future', 'gain', 'gallery', 'game', 'gap', 'garage', 'garden', 'gas', 'gate', 'gather',
            'gear', 'general', 'generally', 'generate', 'generation', 'gentle', 'gentleman', 'gently',
            'genuine', 'get', 'gift', 'girl', 'girlfriend', 'give', 'glad', 'glass', 'global',
            'glove', 'goal', 'god', 'gold', 'golden', 'golf', 'good', 'goods', 'government', 'grab',
            'grade', 'gradually', 'grain', 'grand', 'grandfather', 'grandmother', 'grant', 'grass',
            'grateful', 'great', 'greatly', 'green', 'greet', 'grey', 'ground', 'group', 'grow',
            'growth', 'guarantee', 'guard', 'guess', 'guest', 'guide', 'guilty', 'guitar', 'gun',
            'guy', 'habit', 'hair', 'half', 'hall', 'hand', 'handle', 'hang', 'happen', 'happy',
            'hard', 'hardly', 'harm', 'harmful', 'hat', 'hate', 'have', 'head', 'headline', 'health',
            'healthy', 'hear', 'hearing', 'heart', 'heat', 'heating', 'heavy', 'heel', 'height',
            'helicopter', 'hell', 'hello', 'help', 'helpful', 'hence', 'her', 'here', 'hero',
            'herself', 'hide', 'high', 'highlight', 'highly', 'hill', 'him', 'himself', 'hire',
            'his', 'historic', 'historical', 'history', 'hit', 'hobby', 'hold', 'hole', 'holiday',
            'holy', 'home', 'honest', 'honey', 'honour', 'hook', 'hope', 'hopefully', 'horrible',
            'horror', 'horse', 'hospital', 'host', 'hot', 'hotel', 'hour', 'house', 'household',
            'housing', 'how', 'however', 'huge', 'human', 'humour', 'hundred', 'hungry', 'hunt',
            'hunting', 'hurt', 'husband', 'ice', 'idea', 'ideal', 'identify', 'identity', 'if',
            'ignore', 'ill', 'illegal', 'illness', 'illustrate', 'image', 'imagine', 'immediate',
            'immediately', 'impact', 'impatient', 'implement', 'imply', 'import', 'importance',
            'important', 'impose', 'impossible', 'impress', 'impressed', 'impression', 'impressive',
            'improve', 'improvement', 'in', 'incident', 'include', 'income', 'increase', 'increasingly',
            'incredible', 'indeed', 'independence', 'independent', 'index', 'indicate', 'individual',
            'indoor', 'industrial', 'industry', 'infection', 'inflation', 'influence', 'inform',
            'informal', 'information', 'initial', 'initially', 'initiative', 'injection', 'injury',
            'inner', 'innocent', 'innovation', 'input', 'inquiry', 'insect', 'inside', 'insight',
            'insist', 'inspect', 'inspection', 'inspector', 'inspire', 'install', 'instance',
            'instant', 'instantly', 'instead', 'institute', 'institution', 'instruction', 'instrument',
            'insurance', 'intelligent', 'intend', 'intended', 'intense', 'intention', 'interest',
            'interested', 'interesting', 'internal', 'international', 'internet', 'interpret',
            'interrupt', 'interval', 'interview', 'into', 'introduce', 'introduction', 'investigate',
            'investigation', 'investment', 'invite', 'involve', 'involved', 'iron', 'island', 'issue',
            'it', 'item', 'its', 'itself', 'jacket', 'jail', 'january', 'jazz', 'jealous', 'jeans',
            'job', 'join', 'joint', 'joke', 'journal', 'journalist', 'journey', 'joy', 'judge',
            'judgement', 'juice', 'july', 'jump', 'june', 'junior', 'jury', 'just', 'justice',
            'justify', 'keen', 'keep', 'key', 'keyboard', 'kick', 'kid', 'kill', 'killing', 'kind',
            'king', 'kiss', 'kitchen', 'knee', 'knife', 'knock', 'know', 'knowledge', 'labour',
            'lack', 'lady', 'lake', 'lamp', 'land', 'landscape', 'language', 'lap', 'large',
            'largely', 'laser', 'last', 'late', 'later', 'latest', 'latter', 'laugh', 'launch',
            'law', 'lawyer', 'lay', 'layer', 'lazy', 'lead', 'leader', 'leadership', 'leading',
            'leaf', 'league', 'lean', 'learn', 'learning', 'least', 'leather', 'leave', 'lecture',
            'left', 'leg', 'legal', 'leisure', 'lemon', 'lend', 'length', 'less', 'lesson', 'let',
            'letter', 'level', 'library', 'licence', 'lie', 'life', 'lifestyle', 'lift', 'light',
            'lighting', 'like', 'likely', 'limit', 'limited', 'line', 'link', 'lion', 'lip', 'list',
            'listen', 'literally', 'literature', 'little', 'live', 'living', 'loan', 'local',
            'locate', 'location', 'lock', 'logic', 'logical', 'lonely', 'long', 'look', 'loose',
            'lord', 'lose', 'loss', 'lost', 'lot', 'lots', 'loud', 'love', 'lovely', 'lover',
            'low', 'lower', 'lucky', 'lunch', 'lung', 'machine', 'machinery', 'mad', 'magazine',
            'magic', 'magical', 'mail', 'main', 'mainly', 'maintain', 'maintenance', 'major',
            'majority', 'make', 'maker', 'makeup', 'male', 'mall', 'man', 'manage', 'management',
            'manager', 'manner', 'manufacture', 'manufacturer', 'manufacturing', 'many', 'map',
            'march', 'mark', 'market', 'marketing', 'marriage', 'married', 'marry', 'mass', 'massive',
            'master', 'match', 'material', 'mathematics', 'matter', 'maximum', 'may', 'maybe',
            'mayor', 'me', 'meal', 'mean', 'meaning', 'meanwhile', 'measure', 'measurement', 'meat',
            'mechanical', 'mechanism', 'media', 'medical', 'medicine', 'medium', 'meet', 'meeting',
            'member', 'membership', 'memory', 'mental', 'mention', 'menu', 'merchant', 'mere',
            'merely', 'mess', 'message', 'metal', 'method', 'metre', 'middle', 'might', 'mild',
            'mile', 'military', 'milk', 'mind', 'mine', 'minimum', 'mining', 'minister', 'ministry',
            'minor', 'minority', 'minute', 'miracle', 'mirror', 'miss', 'missile', 'missing',
            'mission', 'mistake', 'mix', 'mixture', 'mobile', 'mode', 'model', 'moderate', 'modern',
            'modest', 'modify', 'moment', 'monday', 'money', 'monitor', 'month', 'mood', 'moon',
            'moral', 'more', 'moreover', 'morning', 'mortgage', 'most', 'mostly', 'mother', 'motor',
            'mount', 'mountain', 'mouse', 'mouth', 'move', 'movement', 'movie', 'much', 'mud',
            'multiple', 'muscle', 'museum', 'music', 'musical', 'musician', 'must', 'my', 'myself',
            'mystery', 'nail', 'naked', 'name', 'narrow', 'nation', 'national', 'native', 'natural',
            'naturally', 'nature', 'navy', 'near', 'nearby', 'nearly', 'neat', 'necessarily',
            'necessary', 'neck', 'need', 'negative', 'negotiate', 'negotiation', 'neighbour',
            'neighbourhood', 'neither', 'nerve', 'nervous', 'net', 'network', 'neutral', 'never',
            'nevertheless', 'new', 'news', 'newspaper', 'next', 'nice', 'night', 'nine', 'nineteen',
            'ninety', 'no', 'noble', 'nobody', 'nod', 'noise', 'nomination', 'none', 'nor', 'normal',
            'normally', 'north', 'northern', 'nose', 'not', 'note', 'nothing', 'notice', 'notion',
            'novel', 'november', 'now', 'nowadays', 'nuclear', 'number', 'numerous', 'nurse',
            'nut', 'object', 'objective', 'obligation', 'observe', 'obtain', 'obvious', 'obviously',
            'occasion', 'occasionally', 'occupation', 'occur', 'ocean', 'october', 'odd', 'of',
            'off', 'offence', 'offend', 'offensive', 'offer', 'office', 'officer', 'official',
            'officially', 'often', 'oil', 'ok', 'old', 'Olympic', 'on', 'once', 'one', 'ongoing',
            'onion', 'online', 'only', 'onto', 'open', 'opening', 'operate', 'operating', 'operation',
            'operational', 'operator', 'opinion', 'opponent', 'opportunity', 'oppose', 'opposite',
            'opposition', 'option', 'or', 'orange', 'order', 'ordinary', 'organ', 'organisation',
            'organise', 'orientation', 'origin', 'original', 'originally', 'other', 'otherwise',
            'ought', 'our', 'ourselves', 'out', 'outcome', 'outdoor', 'outfit', 'outline', 'output',
            'outside', 'outstanding', 'over', 'overall', 'overcome', 'overlap', 'overseas', 'own',
            'owner', 'ownership', 'pace', 'pack', 'package', 'page', 'pain', 'painful', 'paint',
            'painting', 'pair', 'palace', 'pale', 'pan', 'panel', 'paper', 'paragraph', 'parallel',
            'parent', 'park', 'parking', 'parliament', 'part', 'participant', 'participate',
            'participation', 'particular', 'particularly', 'partly', 'partner', 'partnership',
            'party', 'pass', 'passage', 'passenger', 'passion', 'past', 'path', 'patient', 'pattern',
            'pause', 'pay', 'payment', 'peace', 'peaceful', 'peak', 'pen', 'penalty', 'pencil',
            'people', 'pepper', 'per', 'percent', 'percentage', 'perfect', 'perfectly', 'perform',
            'performance', 'performer', 'perhaps', 'period', 'permanent', 'permission', 'permit',
            'person', 'personal', 'personality', 'personally', 'personnel', 'perspective', 'persuade',
            'pet', 'phase', 'philosophy', 'phone', 'photo', 'photograph', 'photographer', 'photography',
            'phrase', 'physical', 'physically', 'piano', 'pick', 'picture', 'piece', 'pilot',
            'pin', 'pink', 'pipe', 'pitch', 'pizza', 'place', 'plain', 'plan', 'plane', 'planet',
            'planning', 'plant', 'plastic', 'plate', 'platform', 'play', 'player', 'playing',
            'pleasant', 'please', 'pleased', 'pleasure', 'plenty', 'plot', 'plus', 'pocket',
            'poem', 'poet', 'poetry', 'point', 'pole', 'police', 'policy', 'political', 'politician',
            'politics', 'poll', 'pollution', 'pool', 'poor', 'pop', 'popular', 'popularity',
            'population', 'port', 'portion', 'portrait', 'pose', 'position', 'positive', 'possess',
            'possession', 'possibility', 'possible', 'possibly', 'post', 'pot', 'potato', 'potential',
            'potentially', 'pound', 'pour', 'poverty', 'powder', 'power', 'powerful', 'practical',
            'practically', 'practice', 'praise', 'pray', 'prayer', 'precise', 'precisely', 'predict',
            'prediction', 'prefer', 'preference', 'pregnant', 'premises', 'premium', 'preparation',
            'prepare', 'prescribe', 'prescription', 'presence', 'present', 'presentation', 'preserve',
            'president', 'press', 'pressure', 'pretend', 'pretty', 'prevent', 'previous', 'previously',
            'price', 'pride', 'priest', 'primary', 'prime', 'prince', 'princess', 'principle',
            'print', 'prior', 'priority', 'prison', 'prisoner', 'privacy', 'private', 'probably',
            'problem', 'procedure', 'proceed', 'process', 'produce', 'producer', 'product', 'production',
            'productive', 'profession', 'professional', 'professor', 'profile', 'profit', 'program',
            'programme', 'progress', 'project', 'promise', 'promote', 'promotion', 'proof', 'proper',
            'properly', 'property', 'proportion', 'proposal', 'propose', 'prospect', 'protect',
            'protection', 'protest', 'proud', 'prove', 'provide', 'provided', 'provision', 'pub',
            'public', 'publication', 'publicity', 'publish', 'publisher', 'pull', 'punch', 'punish',
            'punishment', 'pupil', 'purchase', 'pure', 'purple', 'purpose', 'pursue', 'push', 'put',
            'qualify', 'quality', 'quantity', 'quarter', 'queen', 'question', 'quick', 'quickly',
            'quiet', 'quietly', 'quite', 'quote', 'race', 'racing', 'radio', 'rail', 'railway',
            'rain', 'raise', 'range', 'rank', 'rapid', 'rapidly', 'rare', 'rarely', 'rate', 'rather',
            'rating', 'ratio', 'raw', 'reach', 'react', 'reaction', 'read', 'reader', 'reading',
            'ready', 'real', 'realise', 'realistic', 'reality', 'really', 'reason', 'reasonable',
            'reasonably', 'receive', 'recent', 'recently', 'reception', 'recognise', 'recommend',
            'recommendation', 'record', 'recording', 'recover', 'recovery', 'recruit', 'red', 'reduce',
            'reduction', 'refer', 'reference', 'reflect', 'reflection', 'reform', 'refrigerator',
            'refuse', 'regard', 'regarding', 'regardless', 'region', 'regional', 'register',
            'registration', 'regular', 'regularly', 'regulation', 'reject', 'relate', 'related',
            'relation', 'relationship', 'relative', 'relatively', 'relax', 'relaxed', 'relaxing',
            'release', 'relevant', 'reliable', 'relief', 'religion', 'religious', 'reluctant',
            'rely', 'remain', 'remaining', 'remark', 'remarkable', 'remember', 'remind', 'reminder',
            'removal', 'remove', 'rent', 'repair', 'repeat', 'replace', 'reply', 'report', 'represent',
            'representation', 'representative', 'reputation', 'request', 'require', 'requirement',
            'rescue', 'research', 'reserve', 'resident', 'resolve', 'resource', 'respect', 'respond',
            'response', 'responsibility', 'responsible', 'rest', 'restaurant', 'restore', 'restrict',
            'restriction', 'result', 'retail', 'retain', 'retire', 'retirement', 'return', 'reveal',
            'revenue', 'review', 'revolution', 'reward', 'rich', 'rid', 'ride', 'rider', 'ridiculous',
            'right', 'ring', 'rise', 'risk', 'rival', 'river', 'road', 'rob', 'robot', 'rock',
            'role', 'roll', 'roof', 'room', 'root', 'rope', 'rose', 'rough', 'roughly', 'round',
            'route', 'routine', 'row', 'royal', 'rub', 'rubber', 'rubbish', 'rude', 'rugby',
            'rule', 'ruler', 'rumour', 'run', 'runner', 'running', 'rural', 'rush', 'sad', 'safe',
            'safety', 'sail', 'sailing', 'sake', 'salad', 'salary', 'sale', 'salt', 'same', 'sample',
            'sand', 'satisfaction', 'satisfy', 'satisfied', 'saturday', 'sauce', 'save', 'saving',
            'scale', 'scandal', 'scene', 'schedule', 'scheme', 'scholarship', 'school', 'science',
            'scientific', 'scientist', 'scope', 'score', 'screen', 'script', 'sea', 'search',
            'season', 'seat', 'second', 'secondary', 'secret', 'secretary', 'section', 'sector',
            'secure', 'security', 'see', 'seed', 'seek', 'seem', 'select', 'selection', 'self',
            'sell', 'senate', 'senator', 'send', 'senior', 'sense', 'sensible', 'sensitive', 'sentence',
            'separate', 'sequence', 'series', 'serious', 'seriously', 'serve', 'service', 'session',
            'set', 'setting', 'settle', 'settlement', 'setup', 'seven', 'seventeen', 'seventy',
            'several', 'severe', 'severely', 'sex', 'sexual', 'shade', 'shadow', 'shake', 'shall',
            'shame', 'shape', 'share', 'sharp', 'she', 'sheet', 'shelf', 'shell', 'shelter',
            'shift', 'shine', 'ship', 'shirt', 'shock', 'shocked', 'shocking', 'shoe', 'shoot',
            'shooting', 'shop', 'shopping', 'shore', 'short', 'shot', 'should', 'shoulder', 'shout',
            'show', 'shower', 'shut', 'sick', 'side', 'sight', 'sign', 'signal', 'significant',
            'significantly', 'silence', 'silent', 'silly', 'silver', 'similar', 'similarly',
            'simple', 'simply', 'since', 'sing', 'singer', 'singing', 'single', 'sink', 'sir',
            'sister', 'sit', 'site', 'sitting', 'situation', 'six', 'sixteen', 'sixty', 'size',
            'skill', 'skin', 'sky', 'sleep', 'sleeping', 'slice', 'slide', 'slight', 'slightly',
            'slip', 'slow', 'slowly', 'small', 'smart', 'smell', 'smile', 'smoke', 'smoking',
            'smooth', 'snap', 'snow', 'so', 'soap', 'social', 'society', 'sock', 'soft', 'software',
            'soil', 'solar', 'sold', 'sole', 'solid', 'solution', 'solve', 'some', 'somebody',
            'somehow', 'someone', 'something', 'sometimes', 'somewhat', 'somewhere', 'son', 'song',
            'soon', 'sophisticated', 'sore', 'sort', 'soul', 'sound', 'soup', 'source', 'south',
            'southern', 'space', 'spare', 'speak', 'speaker', 'speaking', 'special', 'specialist',
            'specially', 'species', 'specific', 'specifically', 'speech', 'speed', 'spell',
            'spend', 'spending', 'spin', 'spirit', 'spite', 'split', 'sport', 'spot', 'spread',
            'spring', 'square', 'squeeze', 'stable', 'staff', 'stage', 'stain', 'stair', 'stake',
            'stand', 'standard', 'standing', 'star', 'stare', 'start', 'state', 'statement',
            'station', 'status', 'stay', 'steady', 'steal', 'steam', 'steel', 'step', 'stick',
            'still', 'stir', 'stock', 'stomach', 'stone', 'stop', 'storage', 'store', 'storm',
            'story', 'straight', 'strain', 'strand', 'strange', 'stranger', 'strategy', 'stream',
            'street', 'strength', 'strengthen', 'stress', 'stretch', 'strike', 'string', 'strip',
            'stroke', 'strong', 'strongly', 'structure', 'struggle', 'stuck', 'student', 'studio',
            'study', 'stuff', 'stupid', 'style', 'subject', 'subsequent', 'substance', 'substantial',
            'substitute', 'succeed', 'success', 'successful', 'successfully', 'such', 'sudden',
            'suddenly', 'sue', 'suffer', 'sufficient', 'sugar', 'suggest', 'suggestion', 'suit',
            'suitable', 'sum', 'summary', 'summer', 'sun', 'sunday', 'super', 'superior', 'supply',
            'support', 'supporter', 'suppose', 'sure', 'surely', 'surface', 'surgery', 'surprise',
            'surprised', 'surprising', 'surprisingly', 'surround', 'surrounding', 'survey',
            'survival', 'survive', 'survivor', 'suspect', 'suspend', 'suspicious', 'sustain',
            'swap', 'swear', 'sweat', 'sweep', 'sweet', 'swim', 'swimming', 'swing', 'switch',
            'symbol', 'sympathy', 'system', 'table', 'tackle', 'tail', 'take', 'tale', 'talent',
            'talk', 'tall', 'tank', 'tap', 'tape', 'target', 'task', 'taste', 'tax', 'taxi',
            'tea', 'teach', 'teacher', 'teaching', 'team', 'tear', 'technical', 'technique',
            'technology', 'telephone', 'television', 'tell', 'temperature', 'temple', 'temporary',
            'ten', 'tend', 'tendency', 'tennis', 'tension', 'tent', 'term', 'terminal', 'terms',
            'terrible', 'territory', 'terror', 'test', 'text', 'than', 'thank', 'thanks', 'that',
            'the', 'theatre', 'their', 'them', 'theme', 'themselves', 'then', 'theory', 'there',
            'therefore', 'these', 'they', 'thick', 'thin', 'thing', 'think', 'thinking', 'third',
            'thirteen', 'thirty', 'this', 'thorough', 'thoroughly', 'those', 'though', 'thought',
            'thousand', 'threat', 'threaten', 'three', 'threw', 'through', 'throughout', 'throw',
            'thumb', 'thursday', 'thus', 'ticket', 'tide', 'tie', 'tight', 'time', 'timing',
            'tiny', 'tip', 'tire', 'tired', 'tissue', 'title', 'to', 'tobacco', 'today', 'toe',
            'together', 'tomorrow', 'tone', 'tongue', 'tonight', 'too', 'tool', 'tooth', 'top',
            'topic', 'total', 'totally', 'touch', 'tough', 'tour', 'tourist', 'tournament', 'towards',
            'town', 'toy', 'track', 'trade', 'trading', 'tradition', 'traditional', 'traffic',
            'train', 'training', 'transfer', 'transform', 'transformation', 'transport', 'transportation',
            'trap', 'travel', 'treat', 'treatment', 'tree', 'trial', 'trick', 'trip', 'trouble',
            'truck', 'true', 'truly', 'trust', 'truth', 'try', 'tube', 'tuesday', 'tune', 'turn',
            'turning', 'twelve', 'twenty', 'twice', 'twin', 'two', 'type', 'typical', 'typically',
            'ugly', 'ultimate', 'ultimately', 'unable', 'uncle', 'under', 'understand', 'understanding',
            'undertake', 'unemployment', 'unfortunately', 'union', 'unique', 'unit', 'united',
            'unity', 'universe', 'university', 'unknown', 'unless', 'unlike', 'unlikely', 'until',
            'unusual', 'up', 'upon', 'upper', 'urban', 'urge', 'urgent', 'us', 'use', 'used',
            'useful', 'user', 'usual', 'usually', 'vacation', 'valley', 'valuable', 'value',
            'van', 'variety', 'various', 'vast', 'vegetable', 'vehicle', 'version', 'versus',
            'very', 'via', 'victim', 'video', 'view', 'village', 'violence', 'violent', 'virtual',
            'virus', 'visible', 'vision', 'visit', 'visitor', 'visual', 'vital', 'voice', 'volume',
            'vote', 'wage', 'wait', 'wake', 'walk', 'walking', 'wall', 'want', 'war', 'ward',
            'warm', 'warn', 'warning', 'wash', 'waste', 'watch', 'water', 'wave', 'way', 'we',
            'weak', 'weakness', 'wealth', 'weapon', 'wear', 'weather', 'web', 'website', 'wedding',
            'wednesday', 'week', 'weekend', 'weekly', 'weight', 'welcome', 'welfare', 'well',
            'west', 'western', 'wet', 'what', 'whatever', 'wheel', 'when', 'whenever', 'where',
            'whereas', 'wherever', 'whether', 'which', 'while', 'whilst', 'white', 'who', 'whoever',
            'whole', 'whom', 'whose', 'why', 'wide', 'widely', 'wife', 'wild', 'will', 'willing',
            'win', 'wind', 'window', 'wine', 'wing', 'winner', 'winning', 'winter', 'wire',
            'wise', 'wish', 'with', 'withdraw', 'within', 'without', 'witness', 'woman', 'women',
            'won', 'wonder', 'wonderful', 'wood', 'wooden', 'wool', 'word', 'work', 'worker',
            'working', 'workplace', 'workshop', 'world', 'worldwide', 'worried', 'worry', 'worse',
            'worship', 'worst', 'worth', 'would', 'write', 'writer', 'writing', 'wrong', 'yard',
            'yeah', 'year', 'yellow', 'yes', 'yesterday', 'yet', 'yield', 'you', 'young', 'your',
            'yours', 'yourself', 'youth', 'zone'
        }
    
    def _get_b2_words(self):
        """B2 Upper-intermediate level words"""
        return {
            'abandon', 'absolute', 'absorb', 'abstract', 'academic', 'accent', 'acceptable', 'accidentally',
            'accommodate', 'accompany', 'accomplish', 'account', 'accurate', 'accuse', 'acknowledge',
            'acquire', 'activate', 'actual', 'adapt', 'addiction', 'additional', 'address', 'adequate',
            'adjust', 'administration', 'adopt', 'advance', 'affair', 'affordable', 'agency', 'agenda',
            'aggressive', 'agriculture', 'aid', 'aircraft', 'alarm', 'alter', 'altogether', 'ambitious',
            'analyse', 'ancient', 'angle', 'anniversary', 'annual', 'anticipate', 'anxious', 'appeal',
            'appear', 'applicable', 'appoint', 'appreciate', 'approach', 'appropriate', 'approximately',
            'architectural', 'argue', 'arise', 'arrange', 'arrest', 'artificial', 'artistic', 'aspect',
            'assess', 'assign', 'assist', 'associate', 'assume', 'assure', 'attach', 'attempt',
            'attend', 'attitude', 'attract', 'attractive', 'attribute', 'auction', 'audience', 'authentic',
            'author', 'authority', 'automatic', 'available', 'average', 'avoid', 'award', 'aware',
            'back', 'bacteria', 'badge', 'balanced', 'barely', 'bargain', 'barrier', 'basically',
            'battle', 'bear', 'beat', 'beneficial', 'beside', 'bias', 'biological', 'blame', 'blind',
            'blow', 'border', 'broadcast', 'budget', 'bulk', 'burst', 'cabinet', 'calculate', 'cancel',
            'capacity', 'capture', 'carbon', 'career', 'careful', 'careless', 'carry', 'case', 'cast',
            'casual', 'category', 'celebrate', 'chain', 'challenge', 'champion', 'channel', 'character',
            'characteristic', 'charge', 'chart', 'chemical', 'chest', 'choice', 'circumstance', 'citizen',
            'civil', 'clarify', 'classic', 'classify', 'climate', 'climb', 'close', 'code', 'coin',
            'collapse', 'colleague', 'collect', 'combination', 'combine', 'command', 'comment',
            'commercial', 'commission', 'commit', 'commitment', 'committee', 'communicate', 'community',
            'companion', 'compare', 'compete', 'complex', 'component', 'compose', 'compound', 'comprehensive',
            'compute', 'conceive', 'concept', 'concern', 'conclude', 'concrete', 'conduct', 'conference',
            'confidence', 'confirm', 'conflict', 'confuse', 'connect', 'conscious', 'consequence',
            'conservative', 'consider', 'consist', 'constant', 'constitute', 'construct', 'consume',
            'contact', 'contain', 'contemporary', 'content', 'contest', 'context', 'contract', 'contrast',
            'contribute', 'controversial', 'convention', 'convert', 'convince', 'cooperate', 'cope',
            'corporate', 'correct', 'correspond', 'cost', 'council', 'count', 'counter', 'couple',
            'courage', 'course', 'cover', 'craft', 'crash', 'create', 'creative', 'credit', 'crime',
            'crisis', 'criterion', 'critical', 'crop', 'crucial', 'culture', 'cure', 'curious',
            'current', 'curve', 'custom', 'cycle', 'damage', 'data', 'debate', 'debt', 'decade',
            'decide', 'declare', 'decline', 'decorate', 'decrease', 'dedicate', 'defeat', 'defend',
            'define', 'degree', 'delay', 'deliver', 'demonstrate', 'deny', 'depend', 'deposit',
            'depression', 'derive', 'describe', 'design', 'desire', 'despite', 'destroy', 'detect',
            'determine', 'develop', 'device', 'diagnose', 'dialogue', 'diet', 'digital', 'dimension',
            'direct', 'discipline', 'discover', 'discuss', 'disease', 'dismiss', 'display', 'distribute',
            'diverse', 'divide', 'document', 'domestic', 'dominate', 'donate', 'draft', 'drama',
            'dramatic', 'draw', 'drug', 'duty', 'dynamic', 'economic', 'edit', 'educate', 'effect',
            'efficient', 'effort', 'elaborate', 'elect', 'element', 'eliminate', 'emerge', 'emotion',
            'emphasis', 'employ', 'enable', 'encounter', 'encourage', 'end', 'energy', 'engage',
            'engine', 'enhance', 'enormous', 'enquiry', 'ensure', 'enterprise', 'entertain', 'entire',
            'environment', 'episode', 'equal', 'equipment', 'equivalent', 'error', 'escape', 'especially',
            'essential', 'establish', 'estimate', 'ethnic', 'evaluate', 'event', 'eventually', 'evidence',
            'evil', 'exact', 'examine', 'example', 'exceed', 'excellent', 'except', 'exchange',
            'exclude', 'excuse', 'execute', 'exercise', 'exist', 'expand', 'expect', 'expensive',
            'experience', 'experiment', 'expert', 'explain', 'explode', 'explore', 'export', 'expose',
            'express', 'extend', 'external', 'extra', 'extreme', 'facility', 'factor', 'factory',
            'fail', 'fair', 'faith', 'familiar', 'fancy', 'farm', 'fashion', 'fault', 'favour',
            'feature', 'federal', 'feed', 'female', 'fence', 'festival', 'fiction', 'field', 'fight',
            'figure', 'file', 'finance', 'find', 'fine', 'firm', 'fish', 'fix', 'flag', 'flat',
            'flexible', 'flight', 'flow', 'focus', 'fold', 'folk', 'follow', 'force', 'foreign',
            'forest', 'forget', 'formal', 'format', 'former', 'formula', 'fortune', 'forum', 'forward',
            'foundation', 'frame', 'fraud', 'free', 'frequency', 'fresh', 'function', 'fund', 'fundamental',
            'funny', 'furniture', 'furthermore', 'future', 'gain', 'gallery', 'gap', 'gather',
            'gear', 'gender', 'general', 'generate', 'genetic', 'gesture', 'gift', 'global', 'goal',
            'goods', 'govern', 'grace', 'grade', 'graduate', 'grand', 'grant', 'grass', 'grave',
            'great', 'gross', 'ground', 'group', 'grow', 'guarantee', 'guard', 'guess', 'guide',
            'guilty', 'habit', 'handle', 'hang', 'hardware', 'harm', 'head', 'heal', 'health',
            'hear', 'heart', 'heat', 'height', 'hell', 'help', 'hence', 'hero', 'hide', 'high',
            'hire', 'historic', 'hit', 'hold', 'honest', 'hook', 'hope', 'horror', 'host', 'house',
            'huge', 'human', 'hunt', 'hurt', 'ideal', 'identify', 'ignore', 'illegal', 'illustrate',
            'image', 'imagine', 'immediate', 'impact', 'implement', 'imply', 'import', 'impose',
            'impress', 'improve', 'incident', 'include', 'income', 'increase', 'incredible', 'indeed',
            'independent', 'index', 'indicate', 'individual', 'industrial', 'industry', 'influence',
            'inform', 'initial', 'initiative', 'injury', 'innovation', 'input', 'insert', 'inside',
            'insight', 'inspect', 'inspire', 'install', 'instance', 'instant', 'instead', 'institute',
            'instruction', 'instrument', 'insurance', 'intelligent', 'intend', 'intense', 'intention',
            'interact', 'interest', 'interface', 'internal', 'international', 'interpret', 'interrupt',
            'interval', 'interview', 'introduce', 'invest', 'investigate', 'invite', 'involve',
            'iron', 'issue', 'item', 'join', 'joint', 'journal', 'journey', 'judge', 'jump',
            'junior', 'jury', 'justice', 'justify', 'keen', 'key', 'kick', 'kind', 'labour',
            'lack', 'land', 'language', 'large', 'laser', 'launch', 'law', 'layer', 'lead',
            'league', 'learn', 'lease', 'least', 'leave', 'lecture', 'legal', 'legend', 'legislation',
            'length', 'level', 'library', 'licence', 'lie', 'lift', 'light', 'limit', 'link',
            'list', 'listen', 'literature', 'load', 'loan', 'local', 'locate', 'location', 'lock',
            'logic', 'long', 'look', 'lord', 'lose', 'loss', 'loud', 'love', 'machine', 'magic',
            'maintain', 'major', 'make', 'male', 'manage', 'manner', 'manufacture', 'map', 'march',
            'mark', 'market', 'marriage', 'mass', 'master', 'match', 'material', 'matter', 'maximum',
            'mean', 'meaning', 'measure', 'mechanism', 'media', 'medical', 'medium', 'meet', 'member',
            'memory', 'mental', 'mention', 'merchant', 'mere', 'mess', 'message', 'metal', 'method',
            'middle', 'military', 'mind', 'mine', 'minimum', 'minister', 'minor', 'minute', 'miracle',
            'mirror', 'miss', 'mission', 'mistake', 'mix', 'mode', 'model', 'moderate', 'modern',
            'modify', 'moment', 'monitor', 'month', 'moral', 'mortgage', 'mother', 'motor', 'mount',
            'move', 'multiple', 'murder', 'muscle', 'museum', 'music', 'mystery', 'naked', 'narrow',
            'nation', 'native', 'natural', 'nature', 'navy', 'near', 'neat', 'necessary', 'neck',
            'need', 'negative', 'negotiate', 'neighbour', 'nerve', 'nervous', 'network', 'neutral',
            'nevertheless', 'news', 'nice', 'noble', 'noise', 'normal', 'north', 'nose', 'notable',
            'note', 'notice', 'notion', 'novel', 'nuclear', 'number', 'numerous', 'nurse', 'object',
            'objective', 'obligation', 'observe', 'obtain', 'obvious', 'occasion', 'occupy', 'occur',
            'ocean', 'offer', 'office', 'officer', 'official', 'oil', 'online', 'only', 'onto',
            'open', 'operate', 'operation', 'opinion', 'opponent', 'opportunity', 'oppose', 'option',
            'order', 'ordinary', 'organ', 'organise', 'origin', 'original', 'other', 'outcome',
            'outdoor', 'output', 'outside', 'overall', 'overcome', 'own', 'owner', 'pace', 'pack',
            'package', 'page', 'pain', 'paint', 'pair', 'palace', 'panel', 'paper', 'parallel',
            'parent', 'park', 'parliament', 'part', 'participate', 'particular', 'partner', 'party',
            'pass', 'passage', 'passenger', 'passion', 'past', 'patch', 'path', 'patient', 'pattern',
            'pause', 'payment', 'peace', 'peak', 'penalty', 'pension', 'people', 'percent', 'perfect',
            'perform', 'period', 'permanent', 'permit', 'person', 'personal', 'perspective', 'persuade',
            'phase', 'philosophy', 'phone', 'photo', 'phrase', 'physical', 'piano', 'pick', 'picture',
            'piece', 'pilot', 'pink', 'pipe', 'pitch', 'place', 'plain', 'plan', 'plane', 'plant',
            'plastic', 'plate', 'platform', 'play', 'pleasant', 'please', 'plot', 'pocket', 'poem',
            'poet', 'point', 'pole', 'police', 'policy', 'political', 'poll', 'pollution', 'pool',
            'popular', 'population', 'port', 'portion', 'portrait', 'pose', 'position', 'positive',
            'possess', 'possibility', 'possible', 'post', 'potential', 'pound', 'pour', 'powder',
            'power', 'practical', 'practice', 'praise', 'pray', 'precise', 'predict', 'prefer',
            'pregnant', 'premium', 'prepare', 'prescribe', 'presence', 'present', 'preserve', 'press',
            'pressure', 'pretend', 'pretty', 'prevent', 'previous', 'price', 'pride', 'primary',
            'prime', 'principle', 'print', 'prior', 'priority', 'prison', 'private', 'probably',
            'problem', 'procedure', 'proceed', 'process', 'produce', 'product', 'production', 'profession',
            'profile', 'profit', 'program', 'progress', 'project', 'promise', 'promote', 'proof',
            'proper', 'property', 'proportion', 'proposal', 'propose', 'prospect', 'protect',
            'protest', 'proud', 'prove', 'provide', 'provision', 'public', 'publication', 'publish',
            'pull', 'punch', 'punish', 'pupil', 'purchase', 'pure', 'purpose', 'pursue', 'push',
            'qualify', 'quality', 'quantity', 'quarter', 'queen', 'question', 'quick', 'quiet',
            'quote', 'race', 'radio', 'rail', 'rain', 'raise', 'range', 'rank', 'rapid', 'rare',
            'rate', 'rather', 'rating', 'ratio', 'reach', 'react', 'read', 'ready', 'real', 'realise',
            'reality', 'reason', 'reasonable', 'receive', 'recent', 'reception', 'recognise', 'recommend',
            'record', 'recover', 'recruit', 'reduce', 'refer', 'reflect', 'reform', 'refuse',
            'regard', 'region', 'register', 'regular', 'regulation', 'reject', 'relate', 'relation',
            'relationship', 'relative', 'relax', 'release', 'relevant', 'reliable', 'relief', 'religion',
            'reluctant', 'rely', 'remain', 'remark', 'remember', 'remind', 'remove', 'rent', 'repair',
            'repeat', 'replace', 'reply', 'report', 'represent', 'reputation', 'request', 'require',
            'rescue', 'research', 'reserve', 'resident', 'resolve', 'resource', 'respect', 'respond',
            'responsibility', 'rest', 'restore', 'restrict', 'result', 'retail', 'retain', 'retire',
            'return', 'reveal', 'revenue', 'review', 'revolution', 'reward', 'rich', 'ride', 'right',
            'ring', 'rise', 'risk', 'rival', 'river', 'road', 'rock', 'role', 'roll', 'roof',
            'room', 'root', 'rope', 'rough', 'round', 'route', 'routine', 'row', 'royal', 'rubber',
            'rule', 'run', 'rural', 'rush', 'safe', 'safety', 'sail', 'sake', 'salary', 'sale',
            'salt', 'sample', 'save', 'scale', 'scandal', 'scene', 'schedule', 'scheme', 'scholarship',
            'school', 'science', 'scope', 'score', 'screen', 'script', 'sea', 'search', 'season',
            'seat', 'second', 'secret', 'section', 'sector', 'secure', 'security', 'seek', 'seem',
            'select', 'self', 'sell', 'senate', 'send', 'senior', 'sense', 'sensible', 'sensitive',
            'sentence', 'separate', 'sequence', 'series', 'serious', 'serve', 'service', 'session',
            'set', 'settle', 'setup', 'several', 'severe', 'sex', 'shade', 'shadow', 'shake',
            'shame', 'shape', 'share', 'sharp', 'shed', 'sheet', 'shelf', 'shell', 'shelter',
            'shift', 'shine', 'ship', 'shirt', 'shock', 'shoe', 'shoot', 'shop', 'shore', 'short',
            'shot', 'shoulder', 'shout', 'show', 'shut', 'sick', 'side', 'sight', 'sign', 'signal',
            'significant', 'silence', 'silly', 'silver', 'similar', 'simple', 'since', 'sing',
            'single', 'sink', 'sister', 'site', 'situation', 'size', 'skill', 'skin', 'sky',
            'sleep', 'slice', 'slide', 'slight', 'slip', 'slow', 'small', 'smart', 'smile', 'smoke',
            'smooth', 'snap', 'snow', 'soap', 'social', 'society', 'sock', 'soft', 'software',
            'soil', 'solar', 'sold', 'solid', 'solution', 'solve', 'somebody', 'somehow', 'someone',
            'something', 'sometimes', 'somewhat', 'somewhere', 'song', 'soon', 'sophisticated',
            'sort', 'soul', 'sound', 'soup', 'source', 'south', 'space', 'spare', 'speak', 'speaker',
            'special', 'species', 'specific', 'speech', 'speed', 'spell', 'spend', 'spin', 'spirit',
            'spite', 'split', 'sport', 'spot', 'spread', 'spring', 'square', 'squeeze', 'stable',
            'staff', 'stage', 'stain', 'stair', 'stake', 'stand', 'standard', 'star', 'stare',
            'start', 'state', 'statement', 'station', 'status', 'stay', 'steady', 'steal', 'steam',
            'steel', 'step', 'stick', 'still', 'stir', 'stock', 'stomach', 'stone', 'stop',
            'storage', 'store', 'storm', 'story', 'straight', 'strain', 'strand', 'strange', 'stranger',
            'strategy', 'stream', 'street', 'strength', 'stress', 'stretch', 'strike', 'string',
            'strip', 'stroke', 'strong', 'structure', 'struggle', 'stuck', 'student', 'studio',
            'study', 'stuff', 'stupid', 'style', 'subject', 'subsequent', 'substance', 'substantial',
            'substitute', 'succeed', 'success', 'successful', 'such', 'sudden', 'sue', 'suffer',
            'sufficient', 'sugar', 'suggest', 'suit', 'suitable', 'summer', 'sun', 'super',
            'superior', 'supply', 'support', 'suppose', 'sure', 'surface', 'surgery', 'surprise',
            'surround', 'survey', 'survive', 'suspect', 'suspend', 'suspicious', 'sustain', 'swap',
            'swear', 'sweat', 'sweep', 'sweet', 'swim', 'swing', 'switch', 'symbol', 'sympathy',
            'system', 'table', 'tackle', 'tail', 'take', 'tale', 'talent', 'talk', 'tall', 'tank',
            'tape', 'target', 'task', 'taste', 'tax', 'taxi', 'teach', 'team', 'tear', 'technical',
            'technique', 'technology', 'telephone', 'television', 'tell', 'temperature', 'temple',
            'temporary', 'tend', 'tennis', 'tension', 'tent', 'term', 'terminal', 'terrible',
            'territory', 'terror', 'test', 'text', 'thank', 'theatre', 'theme', 'theory', 'there',
            'therefore', 'thick', 'thin', 'thing', 'think', 'third', 'thorough', 'though', 'thought',
            'thousand', 'threat', 'three', 'through', 'throughout', 'throw', 'thumb', 'thus',
            'ticket', 'tide', 'tie', 'tight', 'time', 'timing', 'tiny', 'tire', 'tissue', 'title',
            'tobacco', 'today', 'together', 'tomorrow', 'tone', 'tongue', 'tonight', 'tool',
            'tooth', 'topic', 'total', 'touch', 'tough', 'tour', 'tourist', 'tournament', 'towards',
            'town', 'toy', 'track', 'trade', 'tradition', 'traffic', 'train', 'transfer', 'transform',
            'transport', 'trap', 'travel', 'treat', 'treatment', 'tree', 'trial', 'trick', 'trip',
            'trouble', 'truck', 'true', 'trust', 'truth', 'tube', 'tune', 'turn', 'twelve',
            'twenty', 'twice', 'twin', 'type', 'typical', 'ugly', 'ultimate', 'unable', 'uncle',
            'under', 'understand', 'undertake', 'unemployment', 'unfortunately', 'union', 'unique',
            'unit', 'united', 'unity', 'universe', 'university', 'unknown', 'unless', 'unlike',
            'unlikely', 'until', 'unusual', 'upon', 'upper', 'urban', 'urge', 'urgent', 'used',
            'useful', 'user', 'usual', 'usually', 'vacation', 'valley', 'valuable', 'value',
            'variety', 'various', 'vast', 'vegetable', 'vehicle', 'version', 'versus', 'very',
            'victim', 'video', 'view', 'village', 'violence', 'violent', 'virtual', 'virus',
            'visible', 'vision', 'visit', 'visual', 'vital', 'voice', 'volume', 'vote', 'wage',
            'wait', 'wake', 'walk', 'wall', 'want', 'ward', 'warm', 'warn', 'wash', 'waste',
            'watch', 'water', 'wave', 'weak', 'wealth', 'weapon', 'wear', 'weather', 'website',
            'wedding', 'week', 'weekend', 'weight', 'welcome', 'welfare', 'well', 'west', 'wet',
            'what', 'whatever', 'wheel', 'when', 'whenever', 'where', 'whereas', 'wherever',
            'whether', 'which', 'while', 'whilst', 'white', 'whoever', 'whole', 'whom', 'whose',
            'wide', 'wife', 'wild', 'willing', 'wind', 'window', 'wine', 'wing', 'winner',
            'winter', 'wire', 'wise', 'wish', 'withdraw', 'within', 'without', 'witness', 'woman',
            'wonder', 'wonderful', 'wood', 'wooden', 'wool', 'word', 'work', 'worker', 'workplace',
            'workshop', 'world', 'worldwide', 'worried', 'worry', 'worse', 'worship', 'worst',
            'worth', 'would', 'write', 'writer', 'writing', 'wrong', 'yard', 'yeah', 'year',
            'yellow', 'yesterday', 'yield', 'young', 'your', 'yours', 'yourself', 'youth', 'zone'
        }
    
    def _get_c1_words(self):
        """C1 Advanced level words"""
        return {
            'abolish', 'abortion', 'absence', 'absent', 'absurd', 'abuse', 'academy', 'accelerate',
            'acceptance', 'accessible', 'accomplishment', 'accordingly', 'accountability', 'accountable',
            'accumulate', 'accumulation', 'accusation', 'accused', 'acid', 'acquisition', 'activation',
            'activist', 'acute', 'adaptation', 'adhere', 'adjacent', 'adjustment', 'administer',
            'administrative', 'administrator', 'admission', 'adolescent', 'adoption', 'adverse',
            'advocate', 'aesthetic', 'affection', 'aftermath', 'aggression', 'agricultural', 'aide',
            'alert', 'align', 'alignment', 'alike', 'allegation', 'allege', 'allegedly', 'alliance',
            'allocate', 'allocation', 'allowance', 'alongside', 'alter', 'alternative', 'amateur',
            'ambassador', 'ambiguous', 'amendment', 'ancestor', 'anchor', 'angel', 'ankle', 'antenna',
            'anticipation', 'antique', 'apparatus', 'appealing', 'applicable', 'appoint', 'appreciate',
            'approach', 'approval', 'arbitrary', 'architect', 'architectural', 'archive', 'arena',
            'arguably', 'arise', 'arithmetic', 'arrangement', 'array', 'article', 'articulate',
            'artifact', 'artificial', 'artwork', 'ash', 'ashamed', 'aside', 'aspiration', 'assault',
            'assemble', 'assembly', 'assertion', 'assessment', 'asset', 'assign', 'assignment',
            'assistance', 'assistant', 'associate', 'association', 'assumption', 'assurance', 'athlete',
            'athletic', 'atmosphere', 'atomic', 'atrocity', 'attach', 'attachment', 'attain', 'attempt',
            'attendance', 'attendant', 'attorney', 'attribute', 'auction', 'audit', 'aunt', 'authentic',
            'authenticity', 'authority', 'authorization', 'automatic', 'automobile', 'autonomous',
            'autonomy', 'availability', 'avenue', 'aviation', 'awareness', 'awkward', 'bachelor',
            'backup', 'badge', 'balanced', 'ballet', 'balloon', 'ballot', 'bamboo', 'ban', 'bandwidth',
            'bang', 'banner', 'baptism', 'bare', 'barely', 'bargain', 'bark', 'barrel', 'barrier',
            'baseball', 'basement', 'bash', 'basketball', 'batch', 'bathroom', 'battery', 'bay',
            'beam', 'bean', 'bear', 'beard', 'bearing', 'beast', 'beat', 'bedroom', 'beetle',
            'behalf', 'behave', 'behaviour', 'belly', 'bench', 'bend', 'beneficial', 'beside',
            'betray', 'bias', 'bibliography', 'bicycle', 'bid', 'bilateral', 'bill', 'binding',
            'biological', 'biography', 'biology', 'birthday', 'bite', 'bitter', 'bizarre', 'blade',
            'blame', 'blank', 'blanket', 'blast', 'bleeding', 'blend', 'bless', 'blessing', 'blind',
            'block', 'blog', 'blonde', 'bloom', 'blossom', 'blow', 'blueprint', 'blunt', 'blurred',
            'board', 'boast', 'boat', 'boil', 'bold', 'bomb', 'bombing', 'bond', 'bonus', 'boom',
            'boost', 'booth', 'border', 'boring', 'born', 'borrow', 'bottle', 'bottom', 'bounce',
            'boundary', 'bow', 'bowl', 'boxing', 'bracket', 'brain', 'brake', 'branch', 'brand',
            'brass', 'brave', 'breach', 'bread', 'break', 'breakdown', 'breakthrough', 'breast',
            'breath', 'breathe', 'breed', 'breeding', 'brick', 'bride', 'bridge', 'brief', 'briefly',
            'brilliant', 'bring', 'broad', 'broadcast', 'broadly', 'broken', 'bronze', 'brook',
            'brother', 'brown', 'brush', 'brutal', 'bubble', 'bucket', 'buddy', 'budget', 'buffer',
            'bug', 'build', 'builder', 'building', 'bulk', 'bullet', 'bunch', 'bundle', 'burden',
            'bureau', 'burial', 'burn', 'burning', 'burst', 'bury', 'bush', 'business', 'busy',
            'butter', 'button', 'buyer', 'buying', 'buzz', 'cabin', 'cabinet', 'cable', 'cafe',
            'cage', 'cake', 'calculation', 'calendar', 'call', 'calm', 'camera', 'camp', 'campaign',
            'campus', 'canal', 'cancel', 'cancer', 'candidate', 'candle', 'candy', 'canvas',
            'capability', 'capable', 'capacity', 'cape', 'capital', 'capitalism', 'captain', 'capture',
            'carbon', 'card', 'cardiac', 'care', 'career', 'careful', 'carefully', 'careless',
            'cargo', 'carpet', 'carriage', 'carrier', 'carrot', 'carry', 'carve', 'cascade',
            'cast', 'castle', 'casual', 'cat', 'catalogue', 'catastrophe', 'catch', 'category',
            'cathedral', 'cattle', 'cause', 'caution', 'cave', 'cease', 'ceiling', 'celebrate',
            'celebration', 'celebrity', 'cell', 'cellular', 'cement', 'cemetery', 'census', 'central',
            'centre', 'century', 'cereal', 'ceremony', 'certain', 'certainly', 'certificate',
            'chain', 'chair', 'chairman', 'challenge', 'chamber', 'champion', 'championship',
            'chance', 'chancellor', 'change', 'channel', 'chaos', 'chapel', 'chapter', 'character',
            'characteristic', 'characterize', 'charge', 'charity', 'charm', 'chart', 'charter',
            'chase', 'chat', 'cheap', 'cheat', 'check', 'cheek', 'cheese', 'chemical', 'chemistry',
            'chest', 'chicken', 'chief', 'child', 'childhood', 'chin', 'chip', 'chocolate', 'choice',
            'choose', 'chord', 'chorus', 'chosen', 'chronic', 'chunk', 'church', 'cinema', 'circle',
            'circuit', 'circular', 'circumstance', 'cite', 'citizen', 'citizenship', 'city', 'civil',
            'civilian', 'civilization', 'claim', 'clash', 'class', 'classic', 'classical', 'classification',
            'classify', 'classroom', 'clause', 'clay', 'clean', 'clear', 'clearly', 'clergy',
            'click', 'client', 'cliff', 'climate', 'climb', 'climbing', 'clinic', 'clinical',
            'clock', 'close', 'closely', 'closer', 'closest', 'closure', 'cloth', 'clothes',
            'clothing', 'cloud', 'club', 'clue', 'cluster', 'coach', 'coaching', 'coal', 'coalition',
            'coast', 'coastal', 'coat', 'code', 'coffee', 'cognitive', 'coin', 'coincide', 'cold',
            'collaboration', 'collapse', 'collar', 'colleague', 'collect', 'collection', 'collective',
            'collector', 'college', 'colonial', 'colony', 'colour', 'column', 'combat', 'combination',
            'combine', 'comedy', 'comfort', 'comfortable', 'command', 'commander', 'comment',
            'commentary', 'commentator', 'commerce', 'commercial', 'commission', 'commissioner',
            'commit', 'commitment', 'committee', 'commodity', 'common', 'commonly', 'commonwealth',
            'communicate', 'communication', 'communion', 'communist', 'community', 'compact',
            'companion', 'company', 'comparable', 'comparative', 'compare', 'comparison', 'compartment',
            'compatible', 'compelling', 'compensate', 'compensation', 'compete', 'competence',
            'competent', 'competition', 'competitive', 'competitor', 'compile', 'complain', 'complaint',
            'complement', 'complete', 'completely', 'completion', 'complex', 'complexity', 'compliance',
            'complicate', 'complicated', 'complication', 'compliment', 'comply', 'component',
            'compose', 'composition', 'compound', 'comprehensive', 'comprise', 'compromise', 'compulsory',
            'compute', 'computer', 'computing', 'comrade', 'conceal', 'concede', 'conceive', 'concentrate',
            'concentration', 'concept', 'conception', 'concern', 'concerned', 'concert', 'conclude',
            'conclusion', 'concrete', 'condemn', 'condition', 'conditional', 'conduct', 'conference',
            'confess', 'confession', 'confidence', 'confident', 'confidential', 'configuration',
            'confine', 'confirm', 'confirmation', 'conflict', 'conform', 'confront', 'confrontation',
            'confusion', 'congress', 'congressional', 'connect', 'connection', 'conscience', 'conscious',
            'consciousness', 'consecutive', 'consensus', 'consent', 'consequence', 'consequent',
            'consequently', 'conservation', 'conservative', 'conserve', 'consider', 'considerable',
            'considerably', 'consideration', 'consist', 'consistency', 'consistent', 'consistently',
            'consolidate', 'conspiracy', 'constant', 'constantly', 'constitute', 'constitution',
            'constitutional', 'constrain', 'constraint', 'construct', 'construction', 'constructive',
            'consult', 'consultant', 'consultation', 'consume', 'consumer', 'consumption', 'contact',
            'contain', 'container', 'contamination', 'contemplate', 'contemporary', 'contempt',
            'content', 'contest', 'context', 'continent', 'continental', 'continual', 'continue',
            'continued', 'continuous', 'continuously', 'contract', 'contractor', 'contrary', 'contrast',
            'contribute', 'contribution', 'contributor', 'control', 'controversial', 'controversy',
            'convention', 'conventional', 'conversation', 'conversion', 'convert', 'convey', 'conviction',
            'convince', 'cook', 'cooking', 'cool', 'cooperation', 'cooperative', 'coordinate',
            'coordination', 'coordinator', 'cop', 'cope', 'copper', 'copy', 'copyright', 'core',
            'corn', 'corner', 'corporate', 'corporation', 'correct', 'correction', 'correctly',
            'correlation', 'correspond', 'correspondence', 'correspondent', 'corresponding', 'corridor',
            'corrupt', 'corruption', 'cost', 'costly', 'cottage', 'cotton', 'couch', 'cough',
            'could', 'council', 'councillor', 'counsel', 'counselling', 'count', 'counter', 'counterpart',
            'countless', 'country', 'countryside', 'county', 'coup', 'couple', 'courage', 'course',
            'court', 'courtesy', 'cousin', 'cover', 'coverage', 'cow', 'crack', 'craft', 'crane',
            'crash', 'crazy', 'cream', 'create', 'creation', 'creative', 'creativity', 'creator',
            'creature', 'credibility', 'credit', 'creek', 'crew', 'cricket', 'crime', 'criminal',
            'crisis', 'criteria', 'criterion', 'critic', 'critical', 'critically', 'criticism',
            'criticize', 'crop', 'cross', 'crossing', 'crowd', 'crown', 'crucial', 'crude', 'cruel',
            'cruise', 'crush', 'cry', 'crystal', 'cube', 'cubic', 'cuisine', 'cult', 'cultural',
            'culture', 'cumulative', 'cup', 'cupboard', 'cure', 'curious', 'currency', 'current',
            'currently', 'curriculum', 'curve', 'cushion', 'custody', 'custom', 'customer', 'cut',
            'cute', 'cutting', 'cycle', 'cylinder', 'dad', 'daily', 'dam', 'damage', 'dance',
            'dancer', 'dancing', 'danger', 'dangerous', 'dare', 'dark', 'darkness', 'data', 'database',
            'date', 'dating', 'daughter', 'dawn', 'dead', 'deadline', 'deadly', 'deaf', 'deal',
            'dealer', 'dealing', 'dear', 'death', 'debate', 'debt', 'debut', 'decade', 'decay',
            'decent', 'decide', 'decision', 'deck', 'declaration', 'declare', 'decline', 'decode',
            'decorate', 'decoration', 'decorative', 'decrease', 'dedicate', 'dedicated', 'dedication',
            'deed', 'deem', 'deep', 'deeply', 'deer', 'default', 'defeat', 'defect', 'defence',
            'defend', 'defendant', 'defensive', 'deficit', 'define', 'definite', 'definitely', 'definition',
            'degree', 'delay', 'delegate', 'delegation', 'delete', 'deletion', 'deliberate',
            'deliberately', 'delicate', 'delicious', 'delight', 'deliver', 'delivery', 'demand',
            'democracy', 'democratic', 'demographic', 'demonstrate', 'demonstration', 'denial',
            'dense', 'density', 'dentist', 'deny', 'department', 'departure', 'depend', 'dependent',
            'depict', 'deployment', 'deposit', 'depot', 'depress', 'depressed', 'depressing',
            'depression', 'deprivation', 'deputy', 'derive', 'descendant', 'descent', 'describe',
            'description', 'desert', 'deserve', 'design', 'designate', 'designer', 'desirable',
            'desire', 'desk', 'desktop', 'desperate', 'desperately', 'despite', 'destination',
            'destroy', 'destruction', 'destructive', 'detail', 'detailed', 'detect', 'detection',
            'detective', 'detector', 'detention', 'deteriorate', 'determination', 'determine',
            'determined', 'devastating', 'develop', 'developer', 'development', 'device', 'devise',
            'devote', 'devoted', 'diagram', 'dialogue', 'diamond', 'diary', 'dice', 'dictate',
            'dictionary', 'differ', 'difference', 'different', 'differential', 'differently',
            'difficult', 'difficulty', 'dig', 'digest', 'digital', 'dignity', 'dilemma', 'dimension',
            'dining', 'dinner', 'diplomat', 'diplomatic', 'direct', 'direction', 'directive',
            'directly', 'director', 'directory', 'dirt', 'dirty', 'disability', 'disabled',
            'disadvantage', 'disagree', 'disagreement', 'disappear', 'disappearance', 'disappoint',
            'disappointed', 'disappointing', 'disappointment', 'disaster', 'disc', 'discharge',
            'discipline', 'disclose', 'discount', 'discourse', 'discover', 'discovery', 'discretion',
            'discrimination', 'discuss', 'discussion', 'disease', 'dish', 'dismiss', 'dismissal',
            'disorder', 'dispatch', 'display', 'disposal', 'dispose', 'dispute', 'dissolve',
            'distance', 'distant', 'distinct', 'distinction', 'distinctive', 'distinguish', 'distribute',
            'distribution', 'distributor', 'district', 'disturb', 'disturbance', 'dive', 'diverse',
            'diversity', 'divide', 'dividend', 'division', 'divorce', 'dock', 'doctor', 'doctrine',
            'document', 'documentary', 'documentation', 'dog', 'doll', 'dollar', 'domain', 'dome',
            'domestic', 'dominant', 'dominate', 'domination', 'donate', 'donation', 'door', 'dose',
            'double', 'doubt', 'doubtful', 'down', 'downstairs', 'downtown', 'downward', 'dozen',
            'draft', 'drag', 'drain', 'drainage', 'drama', 'dramatic', 'dramatically', 'draw',
            'drawing', 'dream', 'dress', 'dressed', 'dressing', 'drew', 'dried', 'drift', 'drill',
            'drink', 'drinking', 'drive', 'driver', 'driving', 'drop', 'drove', 'drug', 'drum',
            'drunk', 'dry', 'duck', 'due', 'dull', 'dump', 'duration', 'during', 'dust', 'dust',
            'duty', 'dynamic', 'each', 'eager', 'ear', 'early', 'earn', 'earnings', 'earth',
            'earthquake', 'ease', 'easily', 'east', 'eastern', 'easy', 'eat', 'eating', 'echo',
            'ecological', 'ecology', 'economic', 'economically', 'economics', 'economist', 'economy',
            'edge', 'edit', 'editing', 'edition', 'editor', 'editorial', 'educate', 'education',
            'educational', 'educator', 'effect', 'effective', 'effectively', 'effectiveness',
            'efficiency', 'efficient', 'efficiently', 'effort', 'eight', 'eighteen', 'eighth',
            'eighty', 'either', 'elaborate', 'elderly', 'elect', 'election', 'electoral', 'electric',
            'electrical', 'electricity', 'electronic', 'electronics', 'elegant', 'element', 'elementary',
            'elephant', 'eleven', 'eliminate', 'elimination', 'elite', 'else', 'elsewhere', 'email',
            'embassy', 'embrace', 'emerge', 'emergence', 'emergency', 'emission', 'emotion',
            'emotional', 'emperor', 'emphasis', 'emphasise', 'empire', 'employ', 'employee', 'employer',
            'employment', 'empty', 'enable', 'enact', 'encounter', 'encourage', 'encouragement',
            'encouraging', 'encryption', 'cycle'
        }
    
    def get_level_for_word(self, word: str) -> str:
        """Return the CEFR level for a given word"""
        word_lower = word.lower()
        
        if word_lower in self.vocabulary_levels['A1']:
            return 'A1'
        elif word_lower in self.vocabulary_levels['A2']:
            return 'A2'
        elif word_lower in self.vocabulary_levels['B1']:
            return 'B1'
        elif word_lower in self.vocabulary_levels['B2']:
            return 'B2'
        elif word_lower in self.vocabulary_levels['C1']:
            return 'C1'
        else:
            return 'C2'  # Assume C2 or higher if not found
    
    def get_words_by_level(self, level: str) -> set:
        """Get all words for a specific CEFR level"""
        return self.vocabulary_levels.get(level, set())
    
    def is_appropriate_for_level(self, word: str, target_level: str) -> bool:
        """Check if a word is appropriate for target learning level"""
        word_level = self.get_level_for_word(word)
        level_hierarchy = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']
        
        try:
            word_index = level_hierarchy.index(word_level)
            target_index = level_hierarchy.index(target_level)
            
            # Word should be at target level or one level above
            return word_index >= target_index and word_index <= target_index + 1
        except ValueError:
            return True  # If level not found, include it
    
    def get_all_basic_words(self) -> set:
        """Get all A1 and A2 words (basic vocabulary)"""
        return self.vocabulary_levels['A1'].union(self.vocabulary_levels['A2'])